/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package icx.flight.dialog;

import icx.application.main.sub.FormDistanceCalculation;
import icx.model.DistanceDTO;
import icx.service.AirportService;
import icx.service.impl.AirportDAO;
import icx.service.impl.DistanceDAO;
import icx.util.LoggerUtil;
import icx.util.TimeFactory;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sandaruwan
 */
public class DeleteDistance extends javax.swing.JDialog {

        private JFrame app;
            private static AirportDAO airportDAO;
    private static DistanceDAO distanceDAO;
    private FormDistanceCalculation distancePanel;
//    private String code;
    /**
     * Creates new form AddDistance
     */
    public DeleteDistance(JFrame parent, boolean modal, String action) {
    super(parent, action, modal);
        initComponents();
        airportDAO = new AirportDAO();
        distanceDAO = new DistanceDAO();
        this.app = parent;
        this.distancePanel = this.distancePanel;
        init();
    }
    
    
    public DeleteDistance(JFrame parent, boolean modal, String action, int distanceId, String departureAirport, String arrivalAirport, double distance, Date date, Time time) {
        super(parent, action, modal);
        initComponents();
        airportDAO = new AirportDAO();
        distanceDAO = new DistanceDAO();
        this.app = parent;
        this.distancePanel = this.distancePanel;
        init();
        air1.setSelectedItem(departureAirport);
        air2.setSelectedItem(arrivalAirport);
        this.distanceField.setText(String.valueOf(distance));
    }

    public void init() {
        /**
         * LOAD FROM AIRPORTS
         *
         */
        try {
            airportDAO.loadAllAirportNames(air1, AirportService.DESTINATION.FROM);
        } catch (SQLException e) {
            LoggerUtil.logWarning(e.getMessage());
        }

        /**
         * LOAD TO AIRPORTS
         *
         */
        try {
            airportDAO.loadAllAirportNames(air2, AirportService.DESTINATION.TO);
        } catch (Exception e) {
            LoggerUtil.logWarning(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        air1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        air2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        distanceField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        closeRegister = new javax.swing.JButton();
        processDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(502, 420));
        setSize(new java.awt.Dimension(502, 420));

        jPanel1.setMaximumSize(new java.awt.Dimension(502, 369));
        jPanel1.setPreferredSize(new java.awt.Dimension(502, 369));
        jPanel1.setSize(new java.awt.Dimension(502, 369));

        jLabel2.setText("Fill the details below...");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Delete Distance");

        air1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        air1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                air1ItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Distance");

        air2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        air2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                air2ItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Arrival Airport");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Departure Airport");

        distanceField.setEditable(false);
        distanceField.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N

        closeRegister.setText("Cancel");
        closeRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRegisterActionPerformed(evt);
            }
        });

        processDelete.setText("Delete");
        processDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(distanceField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(air1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(air2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))))
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(air2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(air1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void air1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_air1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_air1ItemStateChanged

    private void air2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_air2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_air2ItemStateChanged

    private void closeRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRegisterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeRegisterActionPerformed

    private void processDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processDeleteActionPerformed
        // TODO add your handling code here:
        if (air1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please Select Departure Airport", "Warning Message", JOptionPane.WARNING_MESSAGE);

        } else if (air2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please Select Arrival Airport", "Warning Message", JOptionPane.WARNING_MESSAGE);

        } else if (distanceField == null || distanceField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Distance", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else {
            DistanceDTO dto = new DistanceDTO();
            dto.setAirport1Id(air1.getSelectedIndex());
            dto.setAirport2Id(air2.getSelectedIndex());
            dto.setDistance(Double.valueOf(distanceField.getText()));
            dto.setCalculationDate(new TimeFactory().getDateTime());

            try {
                DistanceDAO dao = new DistanceDAO();
                dao.deleteDistance(dto.getId());
                JOptionPane.showMessageDialog(this, "Distance Deleted successfully.");
                dispose();
                LoggerUtil.logInfo("THE RECORDE:: " + dto.getAirport1Id() + " TO " + dto.getAirport2Id() + " WAS SUCCESSFULLY DELETED AT: " + dto.getCalculationDate() + " TO " + dto.getDistance() + "|| REFERENCE::" + dto.getId());
                this.dispose();

            } catch (Exception e) {
                LoggerUtil.logSevere(e.getMessage());
            }

        }
    }//GEN-LAST:event_processDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteDistance dialog = new DeleteDistance(new javax.swing.JFrame(), true, "Action");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> air1;
    private javax.swing.JComboBox<String> air2;
    private javax.swing.JButton closeRegister;
    private javax.swing.JTextField distanceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton processDelete;
    // End of variables declaration//GEN-END:variables
}
