package icx.flight;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.ImageIcon;

/**
 *
 * @author sandaruwan
 */
public class FlightCard extends javax.swing.JPanel {

    /**
     * Creates new form FlightCard
     */
    public FlightCard() {
        initComponents();
        airlineIcon.setSvgIcon("icx/resources/flights/svg/airline.svg", 16, 16);
        infoIcon.setSvgIcon("icx/resources/flights/svg/info.svg", 16, 16);
        flightIcon.setSvgIcon("icx/resources/flights/svg/flight.svg", 16, 16);
        setFlightImg();
    }

    public void setFlightImg() {

        String FLIGHT_IMG = "AeroTaxi.svg";
        String PATH = "icx/resources/airline/svg/";

        int maxWidth = 212;
        int maxHeight = 124;
        flightIMG.setIcon(new FlatSVGIcon(PATH+FLIGHT_IMG, maxWidth, maxHeight));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        flightIMG = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        flightID = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        flightIcon = new icx.util.SvgImg();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        airlineIcon = new icx.util.SvgImg();
        jPanel10 = new javax.swing.JPanel();
        airlineText = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        infoIcon = new icx.util.SvgImg();
        jPanel14 = new javax.swing.JPanel();
        infoText = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        actionButton = new javax.swing.JButton();
        waterID = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(224, 265));
        setMinimumSize(new java.awt.Dimension(224, 265));
        setPreferredSize(new java.awt.Dimension(224, 265));
        setSize(new java.awt.Dimension(224, 0));

        jPanel1.setBackground(new java.awt.Color(7, 95, 114));
        jPanel1.setMaximumSize(new java.awt.Dimension(224, 265));
        jPanel1.setMinimumSize(new java.awt.Dimension(224, 265));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(224, 145));
        jPanel3.setMinimumSize(new java.awt.Dimension(224, 145));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(224, 145));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(249, 19));
        jPanel4.setMinimumSize(new java.awt.Dimension(225, 19));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(224, 19));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(24, 32767));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(24, 64));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);

        flightID.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        flightID.setForeground(new java.awt.Color(255, 255, 255));
        flightID.setText("F-0098P");
        flightID.setMaximumSize(new java.awt.Dimension(166, 17));
        flightID.setMinimumSize(new java.awt.Dimension(166, 17));
        flightID.setPreferredSize(new java.awt.Dimension(166, 17));
        jPanel4.add(flightID);

        jPanel9.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel9.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 64));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9);

        flightIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        flightIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        flightIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        jPanel4.add(flightIcon);

        jPanel7.setMaximumSize(new java.awt.Dimension(14, 32767));
        jPanel7.setMinimumSize(new java.awt.Dimension(14, 0));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(14, 64));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);

        jPanel1.add(jPanel4);

        jPanel6.setMaximumSize(new java.awt.Dimension(224, 32));
        jPanel6.setMinimumSize(new java.awt.Dimension(224, 32));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(224, 32));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setMaximumSize(new java.awt.Dimension(14, 32767));
        jPanel11.setMinimumSize(new java.awt.Dimension(14, 0));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(14, 64));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11);

        airlineIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        airlineIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        airlineIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        jPanel6.add(airlineIcon);

        jPanel10.setMaximumSize(new java.awt.Dimension(5, 32767));
        jPanel10.setMinimumSize(new java.awt.Dimension(5, 0));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(5, 64));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10);

        airlineText.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        airlineText.setForeground(new java.awt.Color(255, 255, 255));
        airlineText.setText("Sri Lankan Airline");
        airlineText.setPreferredSize(new java.awt.Dimension(176, 17));
        jPanel6.add(airlineText);

        jPanel12.setMaximumSize(new java.awt.Dimension(14, 32767));
        jPanel12.setMinimumSize(new java.awt.Dimension(14, 0));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(14, 64));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel12);

        jPanel1.add(jPanel6);

        jPanel5.setMaximumSize(new java.awt.Dimension(224, 23));
        jPanel5.setMinimumSize(new java.awt.Dimension(224, 23));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(224, 23));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setMaximumSize(new java.awt.Dimension(14, 32767));
        jPanel13.setMinimumSize(new java.awt.Dimension(14, 0));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(14, 64));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel13);

        infoIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        infoIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        infoIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        jPanel5.add(infoIcon);

        jPanel14.setMaximumSize(new java.awt.Dimension(5, 32767));
        jPanel14.setMinimumSize(new java.awt.Dimension(5, 0));
        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(5, 64));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel14);

        infoText.setBackground(new java.awt.Color(242, 255, 255));
        infoText.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        infoText.setForeground(new java.awt.Color(166, 197, 204));
        infoText.setText("5 Class 380 Seat Flight... ");
        infoText.setPreferredSize(new java.awt.Dimension(176, 17));
        jPanel5.add(infoText);

        jPanel15.setMaximumSize(new java.awt.Dimension(14, 32767));
        jPanel15.setMinimumSize(new java.awt.Dimension(14, 0));
        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(14, 64));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15);

        jPanel1.add(jPanel5);

        jPanel2.setOpaque(false);

        actionButton.setBackground(new java.awt.Color(255, 245, 210));
        actionButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        actionButton.setForeground(new java.awt.Color(5, 39, 50));
        actionButton.setText("View Details");
        actionButton.setMaximumSize(new java.awt.Dimension(84, 21));
        actionButton.setMinimumSize(new java.awt.Dimension(84, 21));
        actionButton.setPreferredSize(new java.awt.Dimension(84, 21));
        actionButton.setSize(new java.awt.Dimension(84, 21));
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        waterID.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        waterID.setForeground(new java.awt.Color(36, 113, 131));
        waterID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        waterID.setText("A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(waterID)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waterID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private icx.util.SvgImg airlineIcon;
    private javax.swing.JLabel airlineText;
    private javax.swing.JLabel flightID;
    private javax.swing.JLabel flightIMG;
    private icx.util.SvgImg flightIcon;
    private icx.util.SvgImg infoIcon;
    private javax.swing.JLabel infoText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel waterID;
    // End of variables declaration//GEN-END:variables
}
